blueprint:
  name: Laundry Done Alerts v1.12 (status enum, Alexa toggle)
  description: >
    Announces when the washer or dryer finishes by watching status sensors (enum).
    Flow per appliance:
      1) Detect status -> 'running'
      2) Wait until status is one of the configured finish states
         (defaults: 'end', 'power_off', 'off', 'finished')
      3) Announce (if Alexa Alerts toggle is enabled) and optionally push to phone.
  domain: automation
  author: chatgpt
  source_url: https://github.com/rschwarzjr/home-assistant-blueprints/blueprints/automation/laundry_alerts/laundry_done_alerts.yaml
  homeassistant:
    min_version: '2023.9.0'

  input:
    # --- Status sensors (required) ---
    washer_status_sensor:
      name: Washer current status sensor
      description: sensor.washer_current_status (enum; includes 'running' and finish state)
      selector:
        entity:
          domain: sensor

    dryer_status_sensor:
      name: Dryer current status sensor
      description: sensor.dryer_current_status (enum; includes 'running' and finish state)
      selector:
        entity:
          domain: sensor

    # --- Expected enum values (customizable; case-insensitive) ---
    washer_running_state:
      name: Washer "running" state
      default: "running"
      selector:
        text: {}

    washer_finish_states:
      name: Washer finish states (comma-separated)
      description: Any of these will be treated as finished.
      default: "end,power_off,off,finished"
      selector:
        text: {}

    dryer_running_state:
      name: Dryer "running" state
      default: "running"
      selector:
        text: {}

    dryer_finish_states:
      name: Dryer finish states (comma-separated)
      description: Any of these will be treated as finished.
      default: "end,power_off,off,finished"
      selector:
        text: {}

    # --- Alexa / notifications ---
    enable_alexa_alerts:
      name: Alexa Alerts (toggle)
      description: Enable/disable Alexa announcements without editing the automation.
      default: true
      selector:
        boolean: {}

    alexa_targets:
      name: Alexa targets
      description: >
        One or more Alexa media_player entities to receive an announcement
        (Alexa Media Player integration, uses notify.alexa_media).
      selector:
        entity:
          domain: media_player
          multiple: true

    send_phone_notification:
      name: Send phone push notification?
      default: true
      selector:
        boolean: {}

    phone_device:
      name: Phone (Mobile App device)
      description: >
        Pick your phone device (Mobile App integration). We'll try to guess the
        notify service from the device name unless you set an override below.
      default: ""
      selector:
        device:
          integration: mobile_app

    phone_notify_service_override:
      name: (Optional) Override - exact mobile app notify service
      description: >
        If auto-detection fails, paste your full service, e.g. notify.mobile_app_roberts_iphone.
      default: ""
      selector:
        text: {}

    # --- Messaging ---
    announcement_title:
      name: Announcement Title
      default: "Laundry Update"
      selector:
        text: {}

    washer_message:
      name: Washer Finished Message
      default: "The washing machine is done."
      selector:
        text: {}

    dryer_message:
      name: Dryer Finished Message
      default: "The dryer is done."
      selector:
        text: {}

    alexa_method:
      name: Alexa announcement method
      description: "'announce' (tone + announcement) or 'speak' (TTS only)"
      default: announce
      selector:
        select:
          options: [announce, speak]
          mode: dropdown

mode: parallel
max: 10

# ------------------------
# Internal variables
# ------------------------
variables:
  v_title: !input announcement_title
  v_washer_msg: !input washer_message
  v_dryer_msg: !input dryer_message
  v_alexa_method: !input alexa_method

  v_enable_alexa: !input enable_alexa_alerts

  v_send_phone: !input send_phone_notification
  v_phone_device: !input phone_device
  v_phone_service_override: !input phone_notify_service_override

  # Try to guess notify.mobile_app_* from device name if no override
  v_phone_service_autodetected: >-
    {% set d = v_phone_device %}
    {% if d %}
      {% set n = device_attr(d, 'name') | string %}
      {% set slug = n | lower | replace(' ', '_') | replace('-', '_')
                      | regex_replace('[^a-z0-9_]', '') %}
      {{ 'notify.mobile_app_' ~ slug }}
    {% else %}
      {{ '' }}
    {% endif %}
  v_phone_service_final: >-
    {{ v_phone_service_override if v_phone_service_override|length > 0
       else v_phone_service_autodetected }}

  # Bring inputs into variables first (correct usage of !input),
  # then create normalized/lowercased versions via Jinja.
  washer_running_in: !input washer_running_state
  washer_finish_in: !input washer_finish_states
  dryer_running_in: !input dryer_running_state
  dryer_finish_in: !input dryer_finish_states

  washer_running_lc: >-
    {{ washer_running_in | string | lower | trim }}
  washer_finish_list_lc: >-
    {% set s = washer_finish_in | string | lower %}
    {% set s2 = s | replace(' ', '') %}
    {{ s2 | regex_findall('[^,]+') }}
  dryer_running_lc: >-
    {{ dryer_running_in | string | lower | trim }}
  dryer_finish_list_lc: >-
    {% set s = dryer_finish_in | string | lower %}
    {% set s2 = s | replace(' ', '') %}
    {{ s2 | regex_findall('[^,]+') }}

  # Expose entity_ids for templates
  washer_status_id: !input washer_status_sensor
  dryer_status_id: !input dryer_status_sensor

# ------------------------
# Triggers: react to any status change, then branch
# ------------------------
trigger:
  - id: washer_any
    platform: state
    entity_id: !input washer_status_sensor

  - id: dryer_any
    platform: state
    entity_id: !input dryer_status_sensor

condition: []

# ------------------------
# Actions
# ------------------------
action:
  - variables:
      trig_entity: >-
        {{ trigger.to_state.entity_id if trigger is defined else '' }}
      trig_new_lc: >-
        {{ (trigger.to_state.state | string | lower | trim) if trigger is defined else '' }}

  - choose:
      # --- Washer path ---
      - conditions:
          - condition: template
            value_template: >-
              {{ trig_entity == washer_status_id and trig_new_lc == washer_running_lc }}
        sequence:
          # Wait until washer state is in finish list (case-insensitive)
          - wait_template: >-
              {% set cur = states(washer_status_id) | string | lower | trim %}
              {{ cur in washer_finish_list_lc }}
            timeout: "08:00:00"
            continue_on_timeout: false

          # Alexa announcement (toggle-enabled)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_enable_alexa | bool }}"
                sequence:
                  - service: notify.alexa_media
                    data:
                      target: !input alexa_targets
                      message: "{{ v_washer_msg }}"
                      title: "{{ v_title }}"
                      data:
                        type: announce
                        method: "{{ v_alexa_method }}"

          # Optional phone push
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_send_phone | bool }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ v_phone_service_final is string and v_phone_service_final|length > 0 }}
                        sequence:
                          - service: "{{ v_phone_service_final }}"
                            data:
                              title: "{{ v_title }}"
                              message: "{{ v_washer_msg }}"
                    default:
                      - service: persistent_notification.create
                        data:
                          title: "Laundry Done Alerts"
                          message: >-
                            Phone notification skipped. Could not determine a valid
                            mobile app notify service from the selected device.
                            Set the 'Override - exact mobile app notify service' input if needed.

      # --- Dryer path ---
      - conditions:
          - condition: template
            value_template: >-
              {{ trig_entity == dryer_status_id and trig_new_lc == dryer_running_lc }}
        sequence:
          # Wait until dryer state is in finish list (case-insensitive)
          - wait_template: >-
              {% set cur = states(dryer_status_id) | string | lower | trim %}
              {{ cur in dryer_finish_list_lc }}
            timeout: "08:00:00"
            continue_on_timeout: false

          # Alexa announcement (toggle-enabled)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_enable_alexa | bool }}"
                sequence:
                  - service: notify.alexa_media
                    data:
                      target: !input alexa_targets
                      message: "{{ v_dryer_msg }}"
                      title: "{{ v_title }}"
                      data:
                        type: announce
                        method: "{{ v_alexa_method }}"

          # Optional phone push
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ v_send_phone | bool }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ v_phone_service_final is string and v_phone_service_final|length > 0 }}
                        sequence:
                          - service: "{{ v_phone_service_final }}"
                            data:
                              title: "{{ v_title }}"
                              message: "{{ v_dryer_msg }}"
                    default:
                      - service: persistent_notification.create
                        data:
                          title: "Laundry Done Alerts"
                          message: >-
                            Phone notification skipped. Could not determine a valid
                            mobile app notify service from the selected device.
                            Set the 'Override - exact mobile app notify service' input if needed.
