blueprint:
  name: Garage Door Close Button Handler
  description: >
    Closes the matching garage door when you tap the "Close" action in the
    mobile notification created by the Garage Door Open Alerts blueprint.
    Map sensors to covers in the same order.
  domain: automation
  input:
    garage_door_sensors:
      name: Garage Door Sensors
      description: Same sensors used in the alerts blueprint (order matters)
      selector:
        entity:
          multiple: true
          domain: binary_sensor
    garage_door_covers:
      name: Matching Cover Entities
      description: Covers in the same order as sensors
      selector:
        entity:
          multiple: true
          domain: cover

trigger:
  - platform: event
    event_type: mobile_app_notification_action

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.action is string and
         trigger.event.data.action.startswith('CLOSE_') }}

variables:
  sensors: !input garage_door_sensors
  covers: !input garage_door_covers
  map: "{{ dict(zip(sensors, covers)) }}"
  pressed: "{{ trigger.event.data.action[6:] }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pressed in map }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ map[pressed] }}"
    default: []

mode: parallel
