blueprint:
  name: Garage Door Open Alerts (Custom Messages + Close Button)
  description: >
    Sends friendly mobile notifications and/or Alexa announcements when a garage
    door opens, with follow-up reminders if it stays open. Includes a button to
    close the door from the notification. Works with two or more doors.
  domain: automation
  input:
    garage_door_sensors:
      name: Garage Door Sensors
      description: Binary sensors for doors (state 'on' means open)
      selector:
        entity:
          multiple: true
          domain: binary_sensor
    garage_door_covers:
      name: Matching Cover Entities
      description: Covers for each sensor, in the same order
      selector:
        entity:
          multiple: true
          domain: cover
    mobile_notify_service:
      name: Mobile Notification Service
      description: The notify service for your phone (e.g., notify.mobile_app_yourphone)
      selector:
        text:
    alexa_target:
      name: Alexa Device
      description: Alexa media_player entity for announcements
      selector:
        entity:
          domain: media_player
    # Custom messages
    msg_initial:
      name: Initial Alert Message
      default: "Hey! {{ door_name }} was just opened."
      selector:
        text:
    msg_first:
      name: First Reminder Message
      default: "Heads up! {{ door_name }} has been open for {{ first_delay }} minutes."
      selector:
        text:
    msg_second:
      name: Second Reminder Message
      default: "Alert! {{ door_name }} has now been open for {{ second_delay }} minutes."
      selector:
        text:
    # Per-stage delivery toggles
    send_initial_phone:
      name: Send Initial to Phone
      default: true
      selector:
        boolean:
    send_initial_alexa:
      name: Send Initial to Alexa
      default: true
      selector:
        boolean:
    send_first_phone:
      name: Send First Reminder to Phone
      default: true
      selector:
        boolean:
    send_first_alexa:
      name: Send First Reminder to Alexa
      default: true
      selector:
        boolean:
    send_second_phone:
      name: Send Second Reminder to Phone
      default: true
      selector:
        boolean:
    send_second_alexa:
      name: Send Second Reminder to Alexa
      default: true
      selector:
        boolean:
    # Timing controls
    first_delay_minutes:
      name: First reminder after (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 120
          mode: slider
          unit_of_measurement: minutes
    second_delay_minutes:
      name: Second reminder after (minutes)
      description: Total time since open for the second reminder
      default: 60
      selector:
        number:
          min: 2
          max: 240
          mode: slider
          unit_of_measurement: minutes

variables:
  sensor_list: !input garage_door_sensors
  cover_list: !input garage_door_covers
  cover_map: "{{ dict(zip(sensor_list, cover_list)) }}"
  first_delay: !input first_delay_minutes
  second_delay: !input second_delay_minutes
  send_initial_phone: !input send_initial_phone
  send_initial_alexa: !input send_initial_alexa
  send_first_phone: !input send_first_phone
  send_first_alexa: !input send_first_alexa
  send_second_phone: !input send_second_phone
  send_second_alexa: !input send_second_alexa
  msg_initial: !input msg_initial
  msg_first: !input msg_first
  msg_second: !input msg_second
  mobile_notify_service: !input mobile_notify_service
  alexa_target: !input alexa_target

trigger:
  - platform: state
    entity_id: !input garage_door_sensors
    from: 'off'
    to: 'on'

action:
  - variables:
      door_sensor: "{{ trigger.entity_id }}"
      door_name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.to_state.name }}"
      door_cover: "{{ cover_map[trigger.entity_id] }}"

  # Initial Alert
  - parallel:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_initial_phone }}"
            sequence:
              - service: "{{ mobile_notify_service }}"
                data:
                  title: "🚪 Garage Alert"
                  message: "{{ msg_initial }}"
                  data:
                    actions:
                      - action: "CLOSE_{{ door_sensor }}"
                        title: "Close {{ door_name }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_initial_alexa }}"
            sequence:
              - service: notify.alexa_media
                data:
                  target: !input alexa_target
                  message: "{{ msg_initial }}"
                  data:
                    type: announce

  # First Reminder
  - delay: "{{ (first_delay | int) * 60 }}"
  - condition: template
    value_template: "{{ is_state(door_sensor, 'on') }}"
  - parallel:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_first_phone }}"
            sequence:
              - service: "{{ mobile_notify_service }}"
                data:
                  title: "⏱️ Garage Reminder"
                  message: "{{ msg_first }}"
                  data:
                    actions:
                      - action: "CLOSE_{{ door_sensor }}"
                        title: "Close {{ door_name }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_first_alexa }}"
            sequence:
              - service: notify.alexa_media
                data:
                  target: !input alexa_target
                  message: "{{ msg_first }}"
                  data:
                    type: announce

  # Second Reminder
  - variables:
      remaining_minutes: "{{ max((second_delay | int) - (first_delay | int), 0) }}"
  - delay: "{{ remaining_minutes * 60 }}"
  - condition: template
    value_template: "{{ is_state(door_sensor, 'on') }}"
  - parallel:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_second_phone }}"
            sequence:
              - service: "{{ mobile_notify_service }}"
                data:
                  title: "⌛ Garage Still Open"
                  message: "{{ msg_second }}"
                  data:
                    actions:
                      - action: "CLOSE_{{ door_sensor }}"
                        title: "Close {{ door_name }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ send_second_alexa }}"
            sequence:
              - service: notify.alexa_media
                data:
                  target: !input alexa_target
                  message: "{{ msg_second }}"
                  data:
                    type: announce

mode: parallel
max: 10
