blueprint:
  name: Tucker Time Lighting (Brightness Only v1.4)
  description: >
    Say "Alexa, it's Tucker time" to turn on up to 10 lights at specific brightness levels.
    Triggered by an input_boolean helper exposed to Alexa, then auto-resets the helper.
    Notes: Using direct entity_id in service data to ensure repeated triggers work reliably.

  domain: automation
  input:
    alexa_trigger:
      name: Alexa Trigger (Helper)
      description: >
        Input boolean exposed to Alexa. Your Alexa routine should Turn ON this helper
        when you say: "it's tucker time".
      selector:
        entity:
          domain: input_boolean

    transition_seconds:
      name: Transition (seconds)
      description: Optional transition time (if supported).
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

    # -------- Light 1 --------
    light_1:
      name: Light 1
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_1_brightness:
      name: Light 1 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 2 --------
    light_2:
      name: Light 2
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_2_brightness:
      name: Light 2 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 3 --------
    light_3:
      name: Light 3
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_3_brightness:
      name: Light 3 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 4 --------
    light_4:
      name: Light 4
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_4_brightness:
      name: Light 4 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 5 --------
    light_5:
      name: Light 5
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_5_brightness:
      name: Light 5 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 6 --------
    light_6:
      name: Light 6
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_6_brightness:
      name: Light 6 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 7 --------
    light_7:
      name: Light 7
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_7_brightness:
      name: Light 7 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 8 --------
    light_8:
      name: Light 8
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_8_brightness:
      name: Light 8 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 9 --------
    light_9:
      name: Light 9
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_9_brightness:
      name: Light 9 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

    # -------- Light 10 --------
    light_10:
      name: Light 10
      description: Leave blank if unused
      default: []
      selector:
        entity:
          domain: light
    light_10_brightness:
      name: Light 10 Brightness (0–255)
      default: 200
      selector:
        number:
          min: 0
          max: 255
          mode: slider

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input alexa_trigger
    to: "on"

variables:
  l1: !input light_1
  l2: !input light_2
  l3: !input light_3
  l4: !input light_4
  l5: !input light_5
  l6: !input light_6
  l7: !input light_7
  l8: !input light_8
  l9: !input light_9
  l10: !input light_10

action:
  # Light 1
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l1|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_1
              brightness: !input light_1_brightness
              transition: !input transition_seconds

  # Light 2
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l2|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_2
              brightness: !input light_2_brightness
              transition: !input transition_seconds

  # Light 3
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l3|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_3
              brightness: !input light_3_brightness
              transition: !input transition_seconds

  # Light 4
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l4|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_4
              brightness: !input light_4_brightness
              transition: !input transition_seconds

  # Light 5
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l5|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_5
              brightness: !input light_5_brightness
              transition: !input transition_seconds

  # Light 6
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l6|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_6
              brightness: !input light_6_brightness
              transition: !input transition_seconds

  # Light 7
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l7|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_7
              brightness: !input light_7_brightness
              transition: !input transition_seconds

  # Light 8
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l8|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_8
              brightness: !input light_8_brightness
              transition: !input transition_seconds

  # Light 9
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l9|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_9
              brightness: !input light_9_brightness
              transition: !input transition_seconds

  # Light 10
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ l10|length > 0 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_10
              brightness: !input light_10_brightness
              transition: !input transition_seconds

  # Reset helper for next time
  - delay:
      seconds: 1
  - service: input_boolean.turn_off
    target:
      entity_id: !input alexa_trigger
