blueprint:
  name: Tucker Time Lighting (On/Off Lists v1.6)
  description: >
    Say "Alexa, it's Tucker time" to:
      • Turn ON a list of lights to a single chosen brightness (applied to all)
      • Turn OFF a separate list of lights
    Uses a multi-entity selector so you can add/remove lights inline.
    Triggered by an input_boolean exposed to Alexa; auto-resets after running.

  domain: automation
  input:
    alexa_trigger:
      name: Alexa Trigger (Helper)
      description: >
        Input boolean exposed to Alexa. Your Alexa routine should Turn ON this helper
        when you say: "it's tucker time".
      selector:
        entity:
          domain: input_boolean

    # ---- Lights to TURN ON ----
    lights_on:
      name: Lights to Turn ON
      description: >
        Select one or more lights to turn ON. Add as many as you like.
        All selected lights will use the brightness below.
      selector:
        entity:
          domain: light
          multiple: true

    on_brightness:
      name: ON Brightness (1–255)
      description: >
        Brightness applied to ALL lights in "Lights to Turn ON".
        (Tip: 128 ≈ ~50%.)
      default: 200
      selector:
        number:
          min: 1
          max: 255
          mode: slider

    transition_seconds:
      name: Transition (seconds)
      description: Optional fade time for turning ON (if supported).
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

    # ---- Lights to TURN OFF ----
    lights_off:
      name: Lights to Turn OFF
      description: >
        Select one or more lights to turn OFF. Add as many as you like.
      selector:
        entity:
          domain: light
          multiple: true

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input alexa_trigger
    to: "on"

variables:
  _on_list: !input lights_on
  _off_list: !input lights_off

action:
  # Turn ON group (if any selected)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ _on_list is defined and (_on_list | length) > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input lights_on
            data:
              brightness: !input on_brightness
              transition: !input transition_seconds

  # Turn OFF group (if any selected)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ _off_list is defined and (_off_list | length) > 0 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input lights_off

  # Reset helper for next time
  - delay:
      seconds: 1
  - service: input_boolean.turn_off
    target:
      entity_id: !input alexa_trigger
