blueprint:
  name: Tucker Time Lighting (Scene Trigger)
  description: >
    Say "Alexa, it's Tucker time" and this automation will activate a chosen scene.
    Use a scene to set any number of lights with exact brightness, color, and temperature.
    This listens for an input_boolean helper (exposed to Alexa) turning ON, then activates
    the scene and resets the helper back to OFF for the next use.
  domain: automation
  input:
    alexa_trigger:
      name: Alexa Trigger (Helper)
      description: >
        An input_boolean helper exposed to Alexa that turns ON when you say:
        "Alexa, it's Tucker time".
      selector:
        entity:
          domain: input_boolean

    tucker_scene:
      name: Scene to Activate
      description: The scene that contains your exact light settings for "Tucker time".
      selector:
        entity:
          domain: scene

    transition_seconds:
      name: Transition (seconds)
      description: Optional global transition applied when the scene turns on (if supported by devices).
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input alexa_trigger
    to: "on"

action:
  - service: scene.turn_on
    target:
      entity_id: !input tucker_scene
    data:
      transition: !input transition_seconds

  # Small delay so we don't miss rapid re-triggers
  - delay:
      seconds: 1

  # Reset the helper back to OFF for next time
  - service: input_boolean.turn_off
    target:
      entity_id: !input alexa_trigger
      
